### ISSUE TITLE
Heading does not have anchor

### ISSUE THREAD

**Issue by whatisname** [rafgraph/react-markdown-tree#1]
Hi, I really like your program and it is by far my favorite among the alternatives I have found on the Internet. However, I found that anchor does not work like in other tools. I am new to this. If you are still maintaining this repo, could you tell me how to fix it?

For your reference, I have noticed that alternative tools render headings to anchored titles like: `<h1><a href='#api'></a>api</h1>`. How do I apply it to the renderer? (Pardon me if this is a dumb question, I just start to learn React recently) Thank you very much!

**Comment by rafgraph** [comment]
This uses the [`commonmark-react-renderer`](https://github.com/rexxars/commonmark-react-renderer) library for rendering markdown, so any issues like this would be from that library.
